body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Please provide a Twitch.tv Oauth token. Alternatively, you can provide a client ID & secret and one will be automatically retrieved for you.
  - type: input
    attributes:
      name: client_id
      label: 'Client ID:'
      description: Twitch.tv Client ID
  - type: input
    attributes:
      name: client_secret
      label: 'Client Secret:'
      description: Twitch.tv Client Secret
  - type: passwordBox
    attributes:
      name: oauth_token
      label: 'OAuth Token:'
      description: Twitch.tv OAuth Token