body:
  - type: textBlock
    attributes:
      name: description
      description: >
        Please provide a Client ID token and Client Secret (New Twitch API requires a OAuth token).
  - type: input
    attributes:
      name: client_id
      label: 'Client ID:'
      description: Twitch.tv Client ID
  - type: input
    attributes:
      name: client_secret
      label: 'Client Secret:'
      description: Twitch.tv Client Secret
  - type: passwordBox
    attributes:
      name: oauth_token
      label: 'OAuth Token:'
      description: Twitch.tv OAuth Token