name: "test"
on:
  workflow_dispatch:
jobs:
  deps:
    name: "test"
    runs-on: windows-latest
    steps:
      - name: Delete previous drafts
        uses: Garulf/delete-draft-releases@0.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

